#define ssid "BMQQDT"
#define password "bmqqdt123"
#define mqtt_server "mandevices.com"
#define mqtt_topic_pub "attendance/card-register"
#define mqtt_topic_sub "attendance/response"
#define mqtt_user "nhodennn"
#define mqtt_pwd "Abccbdewn"
#define boardStatusTopic "attendance/status"